#!/bin/bash

# ==== FUNCTIONS 

function usage ()
{
    echo "This script allow you to clone a registred repository In order to";
    echo "clone a reposiory, it has to be written in the bin/repolist.txt file";
    echo "following theses conventions : ";
    echo -e "\t - A line should never exceed 3 words.";
    echo -e "\t - The first word represents the website where the repo is.";
    echo -e "\t - The second word is the repository name.";
    echo -e "\t - The last word is the software used to get version the repo.";
    echo -e "\t (Note the this last word is optional if the website is github)";
    echo "";
    echo "Usage : cotorep [options]";
    echo "List options :";
    echo -e "\t -h display help for the program.";
    echo -e "\t -l To display the list of present repositories.";
}

function repo_list () # Should have the repository website in parameter
{
    	echo "Here the complete list of repositories in $1:"
    if [ "$1" == "github" ] ; then 
	repos=$(grep "$1" $HOME/bin/.repolist.txt | cut -d ' ' -f 2);
    elif [ "$1" == "savane" ] ; then
	repos=$(grep "$1" $HOME/bin/.repolist.txt | grep "$2" | cut -d ' ' -f 2);
    fi
    echo "";
    echo -e "$repos \n";
}

function full_repo_list ()
{
    echo "Github registred repositories : "
    grep github $HOME/bin/repolist.txt | cut -d ' ' -f 2; echo "";
    echo "Savane registered repositories using GIT : "
    grep savane $HOME/bin/repolist.txt | grep git | cut -d ' ' -f 2; echo " ";
    echo "Savane registered repositories using SVN : ";
    grep savane $HOME/bin/repolist.txt | grep svn | cut -d ' ' -f 2; echo " ";
}

# ==== CORE

# SVN style :
# svn --username julpilleux co https://services.emi.u-bordeaux.fr/projet/svn/<repo>
# GIT style :
# git clone https://probakilla@github.com/probakilla/<repo>

# If 2 arguments were entered

if [ "$#" -eq 0 ] ; then 
    repo="";
    soft="";
    
    echo "Do you want to clone from Github or savane ?"
    select yn in "Savane" "Github" "Please help, i am a COTOREP !"; do
	case $yn in
	    Github ) repo="github"; break;;
	    Savane ) repo="savane"; break;;
	    "Please help, i am a COTOREP !" ) firefox https://www.youtube.com/watch?v=SIaU1JLGLd4 ; exit;;
	esac
    done
    
    if [ "$repo" == "github" ] ; then
	repo_list "$repo"; # Displaying all repos.;
	
	read -p "Enter a repo name : " name;
	git clone https://probakilla@github.com/probakilla/$name;
	
    elif [ "$repo" == "savane" ] ; then
	echo "Which software do you want to use ?"
	select yn in "GIT" "SVN"; do
	    case $yn in
		GIT ) soft="git"; break;;
		SVN ) soft="svn"; break;;
	    esac
	done
	repo_list "$repo" "$soft"; # Displaying all repos.
	
	read -p "Enter a repo name : " name;
	
	if [ "$soft" == "git" ] ; then
	    git clone https://julpilleux@services.emi.u-bordeaux.fr/projet/git/$name;
	elif [ "$soft" == "svn" ] ; then
	    svn --username julpilleux co https://services.emi.u-bordeaux.fr/projet/svn/$name;
	fi
    fi

elif [ "$#" -eq 1 ] ; then
    if [ "$1" == "-h" ] ; then
	usage;
    elif [ "$1" == "-l" ] ; then
	full_repo_list;
    fi
else
    usage;
fi
