#!/usr/bin/python3

import readline
import json
import getopt
import sys
import os
from os.path import expanduser

repolist = []
home = expanduser("~")
repo_file = home + "/bin/repolist.json"


def help():
    print('This script allows you to clone a registred repositry. The \n')
    print('wanted repository has to be registred in the repolist.json\n')
    print('file.\n\n')
    usage()


def usage():
    help()
    print('USAGE : cotorep [options]\n')
    print('List of options :\n')
    print(' -h To display the help for the script')
    print(' -l To display the full list of repository presents in the file')


def list_repositories():
    with open(repo_file) as json_file:
        json_data = json.load(json_file)

    print('Github repositories :')
    for data in json_data['github']['repolist']:
        print("  " + data)
    print('Savane git repositories :')
    for data in json_data['savane']['git']:
        print("  " + data)
    print('Savane svn repositories')
    for data in json_data['savane']['svn']:
        print("  " + data)


def completer(text, state):
    options = [i for i in repolist if i.startswith(text)]
    if state < len(options):
        return options[state]
    else:
        return None


if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hl", ["help", "list"])
    except getopt.GetoptError as err:
        print(str(err))
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            help()
            sys.exit()
        elif opt in ("-l", "--list"):
            list_repositories()
            sys.exit()

    readline.parse_and_bind("tab: complete")
    readline.set_completer(completer)

    repolist = ["github", "savane"]
    platform = input('Do you want to clone from Github or Savane ?\n')

    if platform == "github":
        with open(repo_file) as json_file:
            json_data = json.load(json_file)
            print('List of Github repositories :')
            for data in json_data[platform]['repolist']:
                print("  " + data)
        repolist = json_data[platform]['repolist']
        repo = input('Chose one repository to clone :\n')
        os.system("git clone https://probakilla@github.com/probakilla/" + repo)

    if platform == "savane":
        with open(repo_file) as json_file:
            json_data = json.load(json_file)
        print('List of Savane repositories : ')
        repolist = ["git", "svn"]
        prog = input('Chose the subversionning program : \nsvn or git ?\n')
        if prog == "git":
            print('List of git repos in Savane :')
            for data in json_data[platform][prog]:
                print("  " + data)
            repolist = json_data[platform][prog]
            repo = input('Which one do you want to clone ?\n')
            os.system("git clone https://julpilleux@services.emi.u-bordeaux.fr/projet/git/" + repo)
        elif prog == "svn":
            print('List of svn repos in Savane :')
            for data in json_data[platform][prog]:
                print("  " + data)
            repolist = json_data[platform][prog]
            repo = input('Which one do you want to clone ?\n')
            os.system("svn --username julpilleux co https://services.emi.u-bordeaux.fr/projet/svn/" + repo)
