#!/bin/bash

function compilation ()
{
    pdflatex $1;
    pdflatex $1;
    pdflatex $1;
}

function usage ()
{
    echo "Usage : cplatex [options] <file_name>.tex"
    echo "Options list :"
    echo -e "\t -b : Compile with BibTex."
    echo -e "\t -c : Clean the latex directory."
    echo -e "\t -d : Display the pdf corresponding to the .tex"
    echo -e "\t -h : Display list of options"
}

function open_pdf()
{
    str=${1::-4}
    echo "Do you want to open $str.pdf?";
    select yn in "Yes" "No";
    do
        case $yn in
            Yes ) evince $str.pdf & break;;
            No  ) break;;
        esac
    done
}


function delete_all ()
{
    str=${1::-4}
    echo -n "Do you want to delete $str.aux, $str.bbl, $str.blg, $str.log,"
    echo " $str.out $str.pdf and $str.toc"
    select yn in "Yes" "No"; do
        case $yn in
            Yes )
                rm -f $str.aux $str.bbl $str.blg $str.log;
                rm $str.out $str.pdf $str.toc;
                break;;
            No  )
                break;;
        esac
    done
}

function check_tex ()
{
    if [ "${1:(-4)}" != ".tex" ] ; then
        echo "Argument must be a '.tex' file.";
        exit 1;
    fi
}

### OPTION PARSING ###

while getopts ":b:c:d:p:h" opt ; do
    case $opt in
        b )
	    check_tex $OPTARG;
	    str=${OPTARG::-4}
            compilation $OPTARG;
            bibtex $str.aux
            compilation $OPTARG;
            break;;
        c )
	    check_tex $OPTARG;
            delete_all $OPTARG;
            break;;
        d )
	    check_tex $OPTARG;
            open_pdf $OPTARG
            break;;
        h )
            usage
            break;;
	p )
	    check_tex $OPTARG;
	    compilation $OPTARG
	    break;;
        \?)
            echo "Invalid option -$OPTARG"
            exit 1;
            break;;
        : )
            echo "Option -$OPTARG requires an argument"
            exit 1;
            break;;
    esac
done
