#!/bin/bash

compilation ()
{
    pdflatex $1;
    pdflatex $1;
    pdflatex $1;
}

usage ()
{
    echo "Usage : cplatex [options] <file_name>.tex"
    echo "Options list :"
    echo -e "\t -b : Compile with BibTex."
    echo -e "\t -c : Clean the latex directory."
    echo -e "\t -d : Display the pdf corresponding to the .tex"
}

open_pdf()
{
    str=${1::-4}
    echo "Do you want to open $str.pdf?";
    select yn in "Yes" "No";
    do
	case $yn in
	    Yes ) evince $str.pdf & break;;
	    No  ) break;;
	esac
    done
}


delete_all ()
{
    str=${1::-4}
    echo "Do you want to delete $str.aux, $str.bbl, $str.blg, $str.log, $str.out $str.pdf and $str.toc"
    select yn in "Yes" "No"; do
	case $yn in
	    Yes ) rm -f $str.aux $str.bbl $str.blg $str.log $str.out $str.pdf $str.toc; break;;
	    No  ) break;;
	esac
    done
}

###Compilation###

# Sans paramètres
if (( $# == 1 )); then
    if [[ "$1" == "-h" ]];then
	usage;
	exit;
    else
	compilation $1;
	exit;
    fi
# Avec Bibliothèque
elif (( $# == 2 )); then
    if [[ "$1" == "-b" ]]; then
	str=${2::-4}
	compilation $str.tex;
	bibtex $str.aux
	compilation $str.tex;
	exit;
    elif [[ "$1" == "-c" ]];then
	delete_all $2;
	exit;
    elif [[ "$1" == "-d" ]]; then
	open_pdf $2;
	exit;
    else
	usage;
	exit;
    fi
else
    usage;
    exit;
fi

