#!/bin/bash

t=('.01' '.05' '.1' '.15' '.2' '.25' '.3' '.35' '.4' '.45' '.5' '.55' '.6' '.65' '.7' '.75' '.8' '.85' '.9' '.95' '1')

nombre=$(tr </dev/urandom -dc 0-20 | head -c1)
feh -xFY --auto-zoom -D${t[$nombre]} ~/bin/images/MPe*
e]} ~/bin/images/MPe*
